### ISSUE TITLE
use node version in an active LTS version.

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/gh-node-module-generatebom#1]
currently node12 is used - see https://github.com/CycloneDX/gh-node-module-generatebom/blob/master/action.yml#L14
better use a active LTS  version - see https://nodejs.org/en/about/releases/

the chosen node version must be compatible to https://github.com/CycloneDX/cyclonedx-node-module
as it is installed and used in the action - see https://github.com/CycloneDX/gh-node-module-generatebom/blob/master/index.js#L28

**Comment by RossMurr4y** [comment]
Node 12 is now deprecated and this is producing warnings when run.

[GitHub blog on deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by jkowalleck** [comment]
if you need this upgrade earlier, then feel free to open a pull-request.
