### ISSUE TITLE
add some tests

### ISSUE THREAD

**Issue by jgadsden** [CycloneDX/gh-node-module-generatebom#8]
it would be good to add some testing, minimal would certainly do the job

[There is an example](https://github.com/anchore/sbom-action/tree/main/tests) of a very fully featured set of tests run by anchore/sbom-action

**Comment by jkowalleck** [comment]
this GH action utilizes external program which is already tested.

**Comment by jgadsden** [comment]
good point @jkowalleck and I will close this issue
